#!/bin/bash
# This script does nothing on a system with dnf & podman.
# It's only useful when deploying TripleO Stein and beyond on CentOS7 and
# Pacemaker enabled.

TIMEOUT=${1:-90}
PARALLEL=${2:-10}

if command -v dnf >/dev/null;then
    if command -v podman >/dev/null; then
        # code that will list remaining containers in podman ps
        # send their names to syslog with logger
    fi
else
    if command -v docker >/dev/null; then
        /usr/bin/docker ps --format \"{{.Names}}\" --filter "label=managed_by=paunch" | \
          /usr/bin/xargs -n 1 -P $PARALLEL /usr/bin/docker stop --time=$TIMEOUT
    fi
fi
