#!/bin/bash
# This script does nothing on a system with dnf & podman.
# It's only useful when deploying TripleO Stein and beyond on CentOS7 and
# Pacemaker enabled.

TIMEOUT=${1:-90}
PARALLEL=${2:-10}

if ! type "dnf" 2>/dev/null;then
    if command -v docker >/dev/null; then
        /usr/bin/docker ps --format \"{{.Names}}\" --filter "label=managed_by=paunch" | \
          /usr/bin/xargs -n 1 -P $PARALLEL /usr/bin/docker stop --time=$TIMEOUT
    fi
fi
